config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :artists, only: [ :index, :show, :edit, :update, :new, :create, :destroy ]

  get '/sobre', to: "pages#sobre"
  root to: 'artists#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :category

  validates :nome, :cidade, :social, :pdf, presence: true
  validates :nome, uniqueness: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :artists

  validates :nome, :icon, presence: true
  validates :nome, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :find_artist, only: [ :show, :edit, :update, :destroy ]

  def index
    @categories = Category.all
    @artists = Artist.all.order(:nome)
    authorize @artists
  end

  def show
    authorize @artist
  end

  def new
    @artist = Artist.new
    authorize @artist
  end

  def create
    @artist = Artist.new(artist_params)
    authorize @artist
    if @artist.save
      redirect_to artist_path(@artist)
    else
      render :new, alert: "Eita, deu ruim. Tente de novo."
    end
  end

  def edit
    authorize @artist
  end

  def update
    authorize @artist
    if @artist.update(artist_params)
      redirect_to artist_path(@artist)
    else
      render :new, alert: "Eita, deu ruim. Tente de novo."
    end
  end

  def destroy
    authorize @artist
    @artist.destroy
    redirect_to artists_path
  end

  private

  def find_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:nome, :cidade, :social, :pdf, :h1, :h2, :h3, :p1, :p2, :p3, :f1, :f2, :f3, :f4, :f1_legenda, :f2_legenda, :f3_legenda, :f4_legenda, :category_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :sobre ]

  def home
  end

  def sobre
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :one_user_registered?, only: [:new, :create]

  protected

  def one_user_registered?
    if User.count == 1
      if user_signed_in?
        redirect_to root_path
      else
        redirect_to new_user_session_path
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_tt_image
    meta_tt_image = (content_for?(:meta_tt_image) ? content_for(:meta_tt_image) : DEFAULT_META["meta_tt_image"])
    # little twist to make it work equally with an asset or a url
    meta_tt_image.starts_with?("http") ? meta_tt_image : image_url(meta_tt_image)
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/artists/edit.html.erb
<div class="artist-form-container">
  <div class="artist-form-card">

    <%= simple_form_for @artist, url: artist_path(@artist), method: 'patch' do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :nome, label: 'Nome do Artista' %>
        <%= f.input :cidade, label: 'Cidade Natal' %>
        <%= f.association :category, label_method: :nome %>
        <%= f.input :social, label: 'Instagram', placeholder: 'manoelmanoel (sem @)' %>
        <%= f.input :pdf, label: 'Link de download do PDF', placeholder: 'www.link-do-pdf-aqui.com' %>
        <%= f.input :f1, label: 'Link da Foto 1', placeholder: 'https://...' %>
        <%= f.input :f1_legenda, label: 'Legenda da Foto 1', :input_html => {:style => 'width: 100%', :rows => 3 } %>
        <%= f.input :f2, label: 'Link da Foto 2', placeholder: 'https://...' %>
        <%= f.input :f2_legenda, label: 'Legenda da Foto 2', :input_html => {:style => 'width: 100%', :rows => 3 } %>
        <%= f.input :f3, label: 'Link da Foto 3', placeholder: 'https://...' %>
        <%= f.input :f3_legenda, label: 'Legenda da Foto 3', :input_html => {:style => 'width: 100%', :rows => 3 } %>
        <%= f.input :f4, label: 'Link da Foto 4', placeholder: 'https://...' %>
        <%= f.input :f4_legenda, label: 'Legenda da Foto 4', :input_html => {:style => 'width: 100%', :rows => 3 } %>
        <%= f.input :h1, label: 'Título 1' %>
        <%= f.input :p1, label: 'Parágrafo - 1', :input_html => {:style => 'width: 100%', :rows => 20 } %>
        <%= f.input :h2, label: 'Título 2' %>
        <%= f.input :p2, label: 'Parágrafo - 2', :input_html => {:style => 'width: 100%', :rows => 20 } %>
        <%= f.input :h3, label: 'Título 3' %>
        <%= f.input :p3, label: 'Parágrafo - 3', :input_html => {:style => 'width: 100%', :rows => 20 } %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, "Publicar", class: 'primary-btn' %>
      </div>
    <% end %>

  </div>
</div>

app/views/artists/index.html.erb
<div class="general-heading">
  <%= image_tag('logo_preto.svg', class: 'logo-preto-home') %>
  <p>É um circuito recortado, polifônico e incompleto de artistas.</p>
</div>

<div class="container-categories-cards">
  <% @categories.each do |c| %>
    <div class="category-tag" id="<%= c.nome.downcase.split(" ").first %>">
      <%= image_tag("#{c.icon}.svg") %>
      <p><%= c.nome %></p>
    </div>
  <% end %>
</div>

<div class="container-artists-cards">
  <% @artists.each do |a| %>
    <% if a.h1 %>

      <%= link_to artist_path(a) do %>
        <div class="artist-card <%= a.category.nome.downcase.split(" ").first %> artist-card-available">
          <div class="artist-card-name">
            <%= image_tag("#{a.category.icon}.svg") %>
            <h4><%= a.nome %></h4>
          </div>
          <p><%= a.cidade %></p>
        </div>
      <% end %>

    <% else %>

      <div class="artist-card <%= a.category.nome.downcase.split(" ").first %> artist-card-unavailable">
        <div class="artist-card-name">
          <%= image_tag("#{a.category.icon}.svg") %>
          <h4><%= a.nome %></h4>
        </div>
        <p><%= a.cidade %></p>
      </div>

    <% end %>
  <% end %>
</div>

app/views/artists/new.html.erb
<div class="artist-form-container">
  <div class="artist-form-card">

    <%= simple_form_for @artist, url: artists_path, method: 'post' do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :nome, label: 'Nome do Artista' %>
        <%= f.input :cidade, label: 'Cidade Natal' %>
        <%= f.association :category, label_method: :nome %>
        <%= f.input :social, label: 'User do Instagram', placeholder: 'manoelmanoel (sem @)' %>
        <%= f.input :pdf, label: 'Link de download do PDF', placeholder: 'www.link-do-pdf-aqui.com' %>
        <%= f.input :f1, label: 'Link da Foto 1', placeholder: 'https://...' %>
        <%= f.input :f1_legenda, label: 'Legenda da Foto 1', :input_html => {:style => 'width: 100%', :rows => 3 } %>
        <%= f.input :f2, label: 'Link da Foto 2', placeholder: 'https://...' %>
        <%= f.input :f2_legenda, label: 'Legenda da Foto 2', :input_html => {:style => 'width: 100%', :rows => 3 } %>
        <%= f.input :f3, label: 'Link da Foto 3', placeholder: 'https://...' %>
        <%= f.input :f3_legenda, label: 'Legenda da Foto 3', :input_html => {:style => 'width: 100%', :rows => 3 } %>
        <%= f.input :f4, label: 'Link da Foto 4', placeholder: 'https://...' %>
        <%= f.input :f4_legenda, label: 'Legenda da Foto 4', :input_html => {:style => 'width: 100%', :rows => 3 } %>
        <%= f.input :h1, label: 'Título 1' %>
        <%= f.input :p1, label: 'Parágrafo - 1', :input_html => {:style => 'width: 100%', :rows => 20 } %>
        <%= f.input :h2, label: 'Título 2' %>
        <%= f.input :p2, label: 'Parágrafo - 2', :input_html => {:style => 'width: 100%', :rows => 20 } %>
        <%= f.input :h3, label: 'Título 3' %>
        <%= f.input :p3, label: 'Parágrafo - 3', :input_html => {:style => 'width: 100%', :rows => 20 } %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, "Publicar", class: 'primary-btn' %>
      </div>
    <% end %>

  </div>
</div>

app/views/artists/show.html.erb
<% content_for :meta_title, "#{@artist.nome} em #{DEFAULT_META["meta_product_name"]}" %>

<div class="artist-info-container">
  <div class="artist-info-name">
    <%= image_tag("#{@artist.category.icon}.svg", class: 'artist-icon') %>
    <h2><%= @artist.nome %></h2>
  </div>
  <h3><%= @artist.cidade %></h3>
</div>

<% if @artist.h1 %>

  <div class="artist-img-container">
    <%= image_tag("#{@artist.f1}", class: 'artist-img') %>
    <p class="artist-img-legenda"><%= @artist.f1_legenda %></p>
  </div>

  <div class="artist-text-content">
    <h1><%= @artist.h1 %></h1>
    <p><%= @artist.p1.html_safe %></p>
  </div>

  <div class="artist-img-container">
    <%= image_tag("#{@artist.f2}", class: 'artist-img') %>
    <p class="artist-img-legenda"><%= @artist.f2_legenda %></p>
  </div>

  <div class="artist-text-content">
    <h1><%= @artist.h2 %></h1>
    <p><%= @artist.p2 %></p>
  </div>

  <div class="artist-img-container">
    <%= image_tag("#{@artist.f3}", class: 'artist-img') %>
    <p class="artist-img-legenda"><%= @artist.f3_legenda %></p>
  </div>

  <div class="artist-text-content">
    <h1><%= @artist.h3 %></h1>
    <p><%= @artist.p3 %></p>
  </div>

  <div class="artist-img-container">
    <%= image_tag("#{@artist.f4}", class: 'artist-img') %>
    <p class="artist-img-legenda"><%= @artist.f4_legenda %></p>
  </div>

<% else %>

  <div class="artist-text-content">
    <h1>Em breve</h1>
    <p>A página desse artista está em construção</p>
  </div>

<% end %>

<hr class="artist-page-solid-dash">

<div class="artist-page-links">
  <%= link_to "http://instagram.com/#{@artist.social}", target: "_blank" do %>
    <div class="artist-link">
      <%= image_tag('social.svg', class: 'social-icon') %>
      <p>@<%= @artist.social %></p>
    </div>
  <% end %>

  <%= link_to "https://#{@artist.pdf}", target: "_blank" do %>
    <div class="artist-link">
      <%= image_tag('download.svg', class: 'social-icon') %>
      <p>download PDF</p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<!--     <title>Boca Miúda</title> -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <title><%= "#{DEFAULT_META["meta_product_name"]}" %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_tt_image %>">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="white-bg">
      <div class="page-container">
        <%= render 'shared/navbar' %>
        <%= yield %>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= image_tag('error-404.svg', class: 'error-icon') %>
<p class="error-p">quem me viu mentiu</p>

app/views/pages/sobre.html.erb
<div class="general-heading">
  <%= image_tag('boca-sobre-2.svg', class: 'sobre-heading-icon') %>
</div>

<div class="sobre-content">
  <h5>Agradecemos a:</h5>
  <p>Ademar de Brito, Ana Pimenta, Camila Bruno, Carolina Lauriano,
  Bruno Oliveira, Bruno Yorka, Brunno Balco, Edu de Barros, Fábio Muniz,
  Fabiano Procópio, Igor Arume, Julia Frederio, Lucas Otsuka, Marcia Barbosa, Rodrigo Rosm e Vitor Gorgulho.</p>

  <h5>Boca Miúda é</h5>
  <p class="colaboradores">Carla Santana,<br>Leonardo Sales,<br>Manoel Manoel<br>e Mulambö</p>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-content-container">
    <div class="footer-content">
      <%= image_tag('logo_branco.svg', class: 'footer-logo') %>
      <div class="footer-icons">
        <%= image_tag('icon-estrela.svg', class: 'icon-estrela') %>
        <%= image_tag('icon-circulo.svg', class: 'footer-icon') %>
        <%= image_tag('icon-triangulo.svg', class: 'footer-icon') %>
        <%= image_tag('icon-quadrado.svg', class: 'footer-icon') %>
      </div>
      <hr class="footer-dash">

      <p class="footer-text">Say hello:<br>fala@bocamiuda.com</p>

      <% if current_user %>
        <% if params[:controller] == 'artists' && params[:action] == 'show'  %>
          <%= link_to "Editar #{@artist.nome}", edit_artist_path(@artist), class: 'adm-links' %>
          <%= link_to "Excluir #{@artist.nome}", artist_path(@artist), data: { confirm: "Certeza que é para excluir?" }, method: :delete, class: 'adm-links' %>
        <% end %>
        <%= link_to "Criar Novo Artista", new_artist_path, class: 'adm-links' %>
        <%= link_to "Sair", destroy_user_session_path, method: :delete, class: 'adm-links' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if current_page?('/') %>
  <div class="boca-navbar">
    <%= link_to "Sobre", sobre_path, class: "sobre-cta" %>
  </div>
<% elsif current_page?('/sobre') %>
  <div class="boca-navbar">
    <%= link_to "Voltar", root_path, class: "voltar-cta" %>
  </div>
<% else %>
  <div class="boca-navbar">
    <%= link_to root_path do %>
      <%= image_tag('logo_preto.svg', class: 'logo-preto') %>
    <% end %>
  </div>
<% end %>